version: '3.7'
services:
  mysql:
    image: mysql:latest
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=knjiznica
    ports:
      - '6306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
